old-version:
  postgres:
    username: mainflux
    password: mainflux
    port: 5432
    host: localhost
    database: users
    ssl-mode: 
    ssl-cert:
    ssl-key:
    ssl-root-cert:
  admin:
    email: admin@example.com
    password: 12345678

new-version:
  clients:
    url: https://localhost:9191
  admin:
    email: admin@example.com
    password: 12345678
